{
 "title": "AppCat SLOs",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(slo:sli_error:ratio_rate1h{sloth_service=~\"appcat-.+\"}, service)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(slo:sli_error:ratio_rate1h{sloth_service=~\"appcat-.+\", service=~\"[[service]]\"},claim_namespace)"
    }
   },
   {
    "name": "name",
    "label": "Name",
    "query": {
     "query": "label_values(slo:sli_error:ratio_rate1h{sloth_service=~\"appcat-.+\", service=~\"[[service]]\", claim_namespace=~\"[[namespace]]\"}, name)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# IMPORTANT\n\n<b>After each change please export this dashboard as JSON and update it in component-appcat repository</b>"
   }
  },
  {
   "title": "SLI",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (min without(prometheus_replica) (slo:sli_error:ratio_rate5m{sloth_service=~\"appcat-.+\", service=~\"[[service]]\", claim_namespace=~\"[[namespace]]\", name=~\"[[name]]\"})) > 0",
     "legendFormat": "{{claim_namespace}}/{{name}}"
    },
    {
     "expr": "min without(prometheus_replica, cluster_id) (slo:objective:ratio{sloth_service=~\"appcat-.+\"})",
     "legendFormat": "Objective"
    }
   ]
  },
  {
   "title": "Month error budget burn chart",
   "type": "timeseries",
   "description": "This graph shows the month error budget burn down chart (starts the 1st until the end of the month)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - sum_over_time(\n  (\n    (1 / (days_in_month() * 24)) *\n    (month() == bool vector(${__to:date:M}))\n  )[32d:1h]\n)",
     "legendFormat": "Ideal constant consumption"
    },
    {
     "expr": " 1- (sum_over_time(\n    (\n       min without(prometheus_replica,instance,pod) (slo:sli_error:ratio_rate1h{sloth_service=~\"appcat-.+\", service=~\"[[service]]\", claim_namespace=~\"[[namespace]]\", name=~\"[[name]]\"})\n       * on() group_left() (\n         month() == bool vector(${__to:date:M})\n       )\n    )[32d:1h]\n  ) / on(sloth_id,cluster_id)  group_left \n        min  without(prometheus_replica,instance,pod) (slo:error_budget:ratio{sloth_service=~\"appcat-.+\"}*on() group_left() (24 * days_in_month()))\n    \n) >0",
     "legendFormat": "{{service}}/{{claim_namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "AppCat Uptime",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - max without(prometheus_replica) (\nsum_over_time(slo:sli_error:ratio_rate5m{sloth_service=~\"appcat-.+\"}[$__range])\n/ ignoring (sloth_window) count_over_time(slo:sli_error:ratio_rate5m{sloth_service=~\"appcat-.+\", service=~\"[[service]]\", claim_namespace=~\"[[namespace]]\", name=~\"[[name]]\"}[$__range])\n) >= 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}