{
 "title": "VSHNPostgreSQL",
 "description": "This dashboard works with postgres_exporter for kube-prometheus-stack.\nThis dashboard is originated by 9628(PostgreSQL Database by Lucas Estienne).",
 "tags": [
  "schedar",
  "Appcat"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "mode", "label": "Lock table" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(appcat_probes_seconds_count{service=\"VSHNPostgreSQL\"},cluster_id)"
    }
   },
   {
    "name": "instance_name",
    "query": {
     "query": "label_values(appcat_probes_seconds_count{service=\"VSHNPostgreSQL\", instance_namespace=\"$instance_namespace\"},name)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(appcat_probes_seconds_count{service=\"VSHNPostgreSQL\", cluster_id=\"$cluster\"},claim_namespace)"
    }
   },
   {
    "name": "instance_namespace",
    "query": {
     "query": "label_values(kube_namespace_labels{cluster_id=\"$cluster\", label_appcat_vshn_io_claim_namespace=\"$namespace\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Important note",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# IMPORTANT\n\n<b>After each change please export this dashboard as JSON and update it in component-appcat repository</b>"
   }
  },
  {
   "title": "SLO",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without(sloth_id, sloth_service) (\n  1 - avg_over_time(\n    slo:sli_error:ratio_rate5m{\n      sloth_service=~\"appcat-.+\", \n      service=\"VSHNPostgreSQL\", \n      name=~\"$instance_name\"\n    }[$__range]\n  )\n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Database(patroni) Memory Usage",
   "type": "timeseries",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_rss{namespace=\"$instance_namespace\",container=\"patroni\"}",
     "legendFormat": "RSS patroni-{{pod}}"
    },
    {
     "expr": "container_memory_working_set_bytes{namespace=\"$instance_namespace\",container=\"patroni\"}",
     "legendFormat": "patroni-{{pod}}"
    }
   ]
  },
  {
   "title": "Secondary Container Memory Usage",
   "type": "timeseries",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"$instance_namespace\", container=~\"cluster-controller|envoy|pgbouncer|postgres-util|prometheus-postgres-exporter\"}",
     "legendFormat": "{{container}}-{{pod}}"
    }
   ]
  },
  {
   "title": "General Counters, CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "Average CPU Usage Percentage",
   "type": "timeseries",
   "description": "CPU usage average",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (pod)(rate(container_cpu_usage_seconds_total{namespace=\"$instance_namespace\",container=\"patroni\"}[$__rate_interval]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Average CPU Usage Rate (all containers)",
   "type": "timeseries",
   "description": "CPU usage average rate",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$instance_namespace\", container!=\"\"}[5m])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Settings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_static{cluster_id=\"$cluster-user-workload\", exported_namespace=\"$instance_namespace\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Shared Buffers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 1, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{namespace=~\"$instance_namespace\"}"
    }
   ]
  },
  {
   "title": "Effective Cache",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_effective_cache_size_bytes{namespace=~\"$instance_namespace\"}"
    }
   ]
  },
  {
   "title": "Maintenance Work Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_maintenance_work_mem_bytes{namespace=~\"$instance_namespace\"}"
    }
   ]
  },
  {
   "title": "Work Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_work_mem_bytes{namespace=~\"$instance_namespace\"}"
    }
   ]
  },
  {
   "title": "Max WAL Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_wal_size_bytes{namespace=~\"$instance_namespace\"}"
    }
   ]
  },
  {
   "title": "Max Worker Processes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_worker_processes{namespace=~\"$instance_namespace\"}"
    }
   ]
  },
  {
   "title": "Max Parallel Workers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_parallel_workers{namespace=~\"$instance_namespace\"}"
    }
   ]
  },
  {
   "title": "Max Connections allowed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_connections{namespace=\"$instance_namespace\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Database Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Active sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{namespace=~\"$instance_namespace\", state=\"active\", datname!~\"template.*\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{namespace=~\"$instance_namespace\", datname!~\"template.*\"}[5m])",
     "legendFormat": "{{datname}} commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{namespace=~\"$instance_namespace\", datname!~\"template.*\"}[5m])",
     "legendFormat": "{{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "Lock tables",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_locks_count{datname!~\"template.*\", namespace=~\"$instance_namespace\"} != 0",
     "legendFormat": "{{datname}},{{mode}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{namespace=~\"$instance_namespace\", datname!~\"template.*\"} / (pg_stat_database_blks_read{namespace=~\"$instance_namespace\", datname!~\"template.*\"} + pg_stat_database_blks_hit{namespace=~\"$instance_namespace\", datname!~\"template.*\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Idle sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (datname) (pg_stat_activity_count{datname!~\"template.*\", namespace=~\"$instance_namespace\", state=~\"idle|idle in transaction|idle in transaction (aborted)\"})",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_conflicts{namespace=~\"$instance_namespace\", datname!~\"template.\"}[5m])",
     "legendFormat": "{{datname}} conflicts"
    },
    {
     "expr": "irate(pg_stat_database_deadlocks{namespace=~\"$instance_namespace\", datname!~\"template.\"}[5m])",
     "legendFormat": "{{datname}} deadlocks"
    }
   ]
  },
  {
   "title": "Temp File (Bytes)",
   "type": "timeseries",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_temp_bytes{namespace=~\"$instance_namespace\", datname!~\"template.*\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Buffers (bgwriter)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend_total{namespace=~\"$instance_namespace\"}[5m])",
     "legendFormat": "buffers_backend"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_alloc_total{namespace=~\"$instance_namespace\"}[5m])",
     "legendFormat": "buffers_alloc"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync_total{namespace=~\"$instance_namespace\"}[5m])",
     "legendFormat": "backend_fsync"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_checkpoint_total{namespace=~\"$instance_namespace\"}[5m])",
     "legendFormat": "buffers_checkpoint"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_clean_total{namespace=~\"$instance_namespace\"}[5m])",
     "legendFormat": "buffers_clean"
    }
   ]
  },
  {
   "title": "Checkpoint Stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 4, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_buffers_checkpoint_total{namespace=~\"$instance_namespace\"}[5m])",
     "legendFormat": "write_time - Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk."
    }
   ]
  }
 ]
}