{
 "title": "VSHN Redis",
 "description": "Redis Dashboard for Prometheus Redis Exporter 1.x, it works with helm stable/redis-ha exporter.If you missing redis memory utilization, please modify \"maxmemory\" value in values.yaml",
 "tags": [
  "prometheus",
  "redis",
  "AppCat"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(appcat_probes_seconds_count{service=\"VSHNRedis\"},cluster_id)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(appcat_probes_seconds_count{cluster_id=\"$cluster\", service=\"VSHNRedis\"},claim_namespace)"
    }
   },
   {
    "name": "name",
    "query": {
     "query": "label_values(appcat_probes_seconds_count{cluster_id=\"$cluster\", claim_namespace=\"$namespace\", service=\"VSHNRedis\"},name)"
    }
   },
   {
    "name": "instance_namespace",
    "query": {
     "query": "label_values(kube_namespace_labels{cluster_id=\"$cluster\", label_appuio_io_billing_name=\"appcat-redis\", label_appcat_vshn_io_claim_namespace=\"$namespace\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# IMPORTANT\n\n<b>After each change please export this dashboard as JSON and update it in component-appcat repository</b>"
   }
  },
  {
   "title": "SLO",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(1 - avg_over_time(slo:sli_error:ratio_rate5m{sloth_service=~\"appcat-.+\", service=\"VSHNRedis\", name=~\"$name\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (min without(prometheus_replica) (slo:sli_error:ratio_rate5m{sloth_service=~\"appcat-.+\", service=\"VSHNRedis\", cluster_id=\"$cluster\", namespace=~\"[[namespace]]\", name=~\"[[name]]\"})) > 0",
     "legendFormat": "{{namespace}}/{{name}}"
    },
    {
     "expr": "min without(prometheus_replica, cluster_id) (slo:objective:ratio{sloth_service=~\"appcat-.+\", cluster_id=\"$cluster\"})",
     "legendFormat": "Objective"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds{namespace=~\"$instance_namespace\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100* (redis_memory_used_bytes{namespace=~\"$instance_namespace\"} / redis_memory_max_bytes{namespace=~\"$instance_namespace\"})"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{namespace=~\"$instance_namespace\"}[1m])"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{namespace=~\"$instance_namespace\"}[5m])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{namespace=~\"$instance_namespace\"}[5m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Redis Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (pod) (redis_memory_used_bytes{namespace=~\"$instance_namespace\"})",
     "legendFormat": "used"
    },
    {
     "expr": "min by (pod) (redis_memory_max_bytes{namespace=~\"$instance_namespace\"})",
     "legendFormat": "max"
    },
    {
     "expr": "max by (pod) (redis_memory_used_rss_bytes{namespace=\"$instance_namespace\"})",
     "legendFormat": "rss"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{namespace=\"$instance_namespace\",container=\"redis\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "min by (pod) (kube_pod_container_resource_limits_memory_bytes{namespace=\"$instance_namespace\",container=\"redis\"})",
     "legendFormat": "Limit {{pod}}"
    },
    {
     "expr": "max by(pod) (container_memory_rss{namespace=\"$instance_namespace\",container=\"redis\"})",
     "legendFormat": "RSS {{pod}}"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by (pod)(rate(container_cpu_usage_seconds_total{namespace=\"$instance_namespace\",container=\"redis\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"$instance_namespace\",container=\"redis\"}",
     "legendFormat": "Limit {{pod}}"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "max by (pod) (redis_connected_clients{namespace=\"$instance_namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total{namespace=~\"$instance_namespace\"} [1m]))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{namespace=~\"$instance_namespace\"}[5m])",
     "legendFormat": "{{ input }}"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{namespace=~\"$instance_namespace\"}[5m])",
     "legendFormat": "{{ output }}"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{namespace=~\"$instance_namespace\"}) by (db)",
     "legendFormat": "{{ db }} "
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{namespace=~\"$instance_namespace\"}[5m])) by (namespaec)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{namespace=~\"$instance_namespace\"}[5m])) by (namespace)",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{namespace=~\"$instance_namespace\"}) - sum (redis_db_keys_expiring{namespace=~\"$instance_namespace\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{namespace=~\"$instance_namespace\"}) ",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Memory Fragmentation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (pod) (redis_mem_fragmentation_bytes{namespace=\"$instance_namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=\"$instance_namespace\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=\"$instance_namespace\"})",
     "legendFormat": "Limit {{{{persistenvolumeclaim}}}}"
    }
   ]
  }
 ]
}