name: Lint
on:
  pull_request:
    branches:
      - master
    paths:
      - component/**
      - packages/**
      - tests/**
      - apis/**

jobs:
  generate-crds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Determine Go version from go.mod
        run: echo "GO_VERSION=$(go mod edit -json | jq -r .Go)" >> $GITHUB_ENV
        working-directory: apis

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run generator
        run: make generate-crd && git diff --exit-code

