name: Pull Request
on:
  pull_request:
    branches:
      - master

env:
  COMPONENT_NAME: appcat

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - lint_jsonnet
          - lint_yaml
          - lint_adoc
    steps:
      - uses: actions/checkout@v4
      - name: Run ${{ matrix.command }}
        run: make ${{ matrix.command }}

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance:
          - defaults
          - exoscale
          - cloudscale
          - openshift
          - vshn
          - apiserver
          - controllers
          - minio
          - cloudscale-metrics-collector-cloud
          - cloudscale-metrics-collector-managed
          - exoscale-metrics-collector-cloud
          - exoscale-metrics-collector-managed
          - control-plane
    defaults:
      run:
        working-directory: ${{ env.COMPONENT_NAME }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ env.COMPONENT_NAME }}
      - name: Compile component
        run: make test -e instance=${{ matrix.instance }}
  golden:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance:
          - defaults
          - exoscale
          - cloudscale
          - openshift
          - vshn
          - apiserver
          - controllers
          - minio
          - cloudscale-metrics-collector-cloud
          - cloudscale-metrics-collector-managed
          - exoscale-metrics-collector-cloud
          - exoscale-metrics-collector-managed
          - control-plane
    defaults:
      run:
        working-directory: ${{ env.COMPONENT_NAME }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ env.COMPONENT_NAME }}
      - name: Golden diff
        run: make golden-diff -e instance=${{ matrix.instance }}
