name: Pull Request
on:
  pull_request:
    branches:
      - master

env:
  COMPONENT_NAME: appcat

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - lint_jsonnet
          - lint_yaml
          - lint_adoc
    steps:
      - uses: actions/checkout@v4
      - name: Run ${{ matrix.command }}
        run: make ${{ matrix.command }}

  golden:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance:
          - vshn-cloud
          - vshn-managed
          - service-cluster
          - control-plane
          - defaults
          - dev
    defaults:
      run:
        working-directory: ${{ env.COMPONENT_NAME }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ env.COMPONENT_NAME }}
          fetch-depth: 0
      - name: Golden diff
        run: make golden-diff -e instance=${{ matrix.instance }}
